[build]
  command = "pip install -r requirements.txt && python -m gunicorn --bind 0.0.0.0:8080 app:app"
  publish = "templates"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
